#!/bin/bash
# Setup Chrome Web Store API credentials for automated publishing
# Usage: ./scripts/setup-credentials.sh

echo "Chrome Web Store API Credentials Setup"
echo "======================================="
echo ""
echo "This script will guide you through setting up credentials for automated publishing."
echo ""
echo "Prerequisites:"
echo "1. A Chrome Web Store developer account"
echo "2. The extension must be uploaded manually FIRST (to get an Extension ID)"
echo ""
echo "Step 1: Create Google Cloud Project & OAuth Credentials"
echo "--------------------------------------------------------"
echo "1. Go to: https://console.cloud.google.com/apis/credentials"
echo "2. Create a new project (e.g., 'chrome-webstore-upload')"
echo "3. Go to 'OAuth consent screen' → Configure as 'External'"
echo "4. Fill in app name and your email, save"
echo "5. Go to 'Credentials' → 'Create Credentials' → 'OAuth client ID'"
echo "6. Choose 'Desktop app', name it, and create"
echo "7. Copy the Client ID and Client Secret"
echo ""
echo "Step 2: Enable Chrome Web Store API"
echo "------------------------------------"
echo "Go to: https://console.cloud.google.com/apis/library/chromewebstore.googleapis.com"
echo "Click 'Enable'"
echo ""
echo "Step 3: Get Refresh Token"
echo "-------------------------"
echo "Run: npx chrome-webstore-upload-keys"
echo "Enter your Client ID and Client Secret when prompted"
echo "Complete the browser OAuth flow"
echo "Copy the Refresh Token from the output"
echo ""
echo "Step 4: Store Credentials"
echo "-------------------------"
echo "Create a .env file (DO NOT COMMIT THIS):"
echo ""
echo "  CLIENT_ID=your_client_id"
echo "  CLIENT_SECRET=your_client_secret"
echo "  REFRESH_TOKEN=your_refresh_token"
echo "  EXTENSION_ID=your_extension_id"
echo ""
echo "Or export them in your shell:"
echo ""
echo "  export CLIENT_ID=your_client_id"
echo "  export CLIENT_SECRET=your_client_secret"
echo "  export REFRESH_TOKEN=your_refresh_token"
echo "  export EXTENSION_ID=your_extension_id"
echo ""
echo "Step 5: Test the Setup"
echo "----------------------"
echo "Run: npm run package"
echo "Run: npm run upload (this will upload without publishing)"
echo ""
echo "For more info: https://github.com/nickytonline/chrome-webstore-upload-keys"
